"""Document Pydantic schemas."""

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, EmailStr, Field, field_validator


class DocumentBase(BaseModel):
    """Base document schema with common fields."""

    title: str = Field(..., min_length=1, max_length=200)
    content: str = Field(..., min_length=1)
    type: str = Field(
        default="specification",
        pattern="^(specification|user_guide|api_doc|readme|changelog|requirements|design|adr|email_template|other)$",
    )
    format: str = Field(default="markdown", pattern="^(markdown|html|text|pdf|docx)$")
    status: str = Field(
        default="draft",
        pattern="^(draft|in_review|approved|published|archived)$",
    )
    version: str | None = Field(None, max_length=20)
    author: EmailStr | None = None
    doc_metadata: dict | None = Field(
        None,
        description="Structured metadata (owner, update_frequency, review_cycle, etc.)",
    )
    assigned_to_type: str | None = Field(
        default=None, pattern="^(user|staff)$", description="Owner type: user or staff"
    )
    assigned_to_id: UUID | None = Field(
        default=None, description="UUID of the assigned user or staff member"
    )

    @field_validator("title")
    @classmethod
    def validate_title(cls, v: str) -> str:
        """Validate document title."""
        if not v.strip():
            raise ValueError("Title cannot be empty or whitespace")
        return v.strip()

    @field_validator("content")
    @classmethod
    def validate_content(cls, v: str) -> str:
        """Validate document content."""
        if not v.strip():
            raise ValueError("Content cannot be empty or whitespace")
        return v


class DocumentCreate(DocumentBase):
    """Schema for creating new documents."""

    project_id: UUID
    document_key: str | None = None  # Generated by service, not set by user
    document_number: int | None = None  # Generated by service, not set by user


class DocumentUpdate(BaseModel):
    """Schema for updating documents (all fields optional)."""

    title: str | None = Field(None, min_length=1, max_length=200)
    content: str | None = Field(None, min_length=1)
    type: str | None = Field(
        None,
        pattern="^(specification|user_guide|api_doc|readme|changelog|requirements|design|adr|other)$",
    )
    format: str | None = Field(None, pattern="^(markdown|html|text|pdf|docx)$")
    status: str | None = Field(
        None,
        pattern="^(draft|in_review|approved|published|archived)$",
    )
    version: str | None = Field(None, max_length=20)
    author: EmailStr | None = None
    doc_metadata: dict | None = None
    assigned_to_type: str | None = Field(None, pattern="^(user|staff)$")
    assigned_to_id: UUID | None = None

    @field_validator("title")
    @classmethod
    def validate_title(cls, v: str | None) -> str | None:
        """Validate document title."""
        if v is not None and not v.strip():
            raise ValueError("Title cannot be empty or whitespace")
        return v.strip() if v else v

    @field_validator("content")
    @classmethod
    def validate_content(cls, v: str | None) -> str | None:
        """Validate document content."""
        if v is not None and not v.strip():
            raise ValueError("Content cannot be empty or whitespace")
        return v


class DocumentResponse(DocumentBase):
    """Schema for document API responses."""

    id: UUID
    document_key: str  # Human-readable key (e.g., "CNTXT-D1")
    document_number: int  # Sequential number within project
    project_id: UUID
    assigned_to_type: str | None
    assigned_to_id: UUID | None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class DocumentSummary(BaseModel):
    """Summary information about a document."""

    id: UUID
    document_key: str  # Human-readable key
    title: str
    type: str
    format: str
    version: str | None = None
    author: str | None = None

    model_config = ConfigDict(from_attributes=True)
