"""Initiative schemas for API request/response models."""

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field


class InitiativeBase(BaseModel):
    """Base schema for Initiative with common fields."""

    name: str = Field(..., min_length=1, max_length=100, description="Initiative name")
    description: str = Field(..., min_length=1, description="Initiative description")
    status: str = Field(
        default="planning",
        pattern="^(planning|in_progress|on_hold|completed|cancelled)$",
        description="Initiative status",
    )
    start_date: datetime | None = Field(None, description="Initiative start date")
    target_date: datetime | None = Field(None, description="Initiative target completion date")
    project_id: UUID | None = Field(None, description="Associated project (optional)")


class InitiativeCreate(InitiativeBase):
    """Schema for creating a new initiative."""

    issue_ids: list[UUID] | None = Field(default=None, description="List of issue IDs to associate")
    tag_ids: list[UUID] | None = Field(default=None, description="List of tag IDs to associate")
    document_ids: list[UUID] | None = Field(
        default=None, description="List of document IDs to associate"
    )
    initiative_key: str | None = None  # Generated by service, not set by user
    initiative_number: int | None = None  # Generated by service, not set by user


class InitiativeUpdate(BaseModel):
    """Schema for updating an initiative."""

    name: str | None = Field(None, min_length=1, max_length=100)
    description: str | None = Field(None, min_length=1)
    status: str | None = Field(None, pattern="^(planning|in_progress|on_hold|completed|cancelled)$")
    start_date: datetime | None = None
    target_date: datetime | None = None
    project_id: UUID | None = None
    issue_ids: list[UUID] | None = None
    tag_ids: list[UUID] | None = None
    document_ids: list[UUID] | None = None


class InitiativeResponse(InitiativeBase):
    """Schema for initiative responses."""

    id: UUID
    initiative_key: str | None  # Human-readable key (e.g., "CNTXT-I1") - None for cross-project initiatives
    initiative_number: int | None  # Sequential number within project - None for cross-project initiatives
    created_at: datetime
    updated_at: datetime
    issue_count: int = Field(default=0, description="Number of associated issues")
    tag_count: int = Field(default=0, description="Number of associated tags")
    document_count: int = Field(default=0, description="Number of associated documents")

    model_config = {"from_attributes": True}
