"""Milestone Pydantic schemas."""

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator


class MilestoneBase(BaseModel):
    """Base milestone schema with common fields."""

    name: str = Field(..., min_length=1, max_length=100)
    description: str = Field(..., min_length=1)
    status: str = Field(
        default="planned", pattern="^(planned|in_progress|completed|cancelled)$"
    )
    start_date: datetime | None = None
    due_date: datetime
    project_id: UUID

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: str) -> str:
        """Validate milestone name."""
        if not v.strip():
            raise ValueError("Name cannot be empty or whitespace")
        return v.strip()

    @field_validator("description")
    @classmethod
    def validate_description(cls, v: str) -> str:
        """Validate milestone description."""
        if not v.strip():
            raise ValueError("Description cannot be empty or whitespace")
        return v.strip()


class MilestoneCreate(MilestoneBase):
    """Schema for creating new milestones."""

    issue_ids: list[UUID] | None = Field(default=None)
    tag_ids: list[UUID] | None = Field(default=None)
    document_ids: list[UUID] | None = Field(default=None)
    milestone_key: str | None = None  # Generated by service, not set by user
    milestone_number: int | None = None  # Generated by service, not set by user


class MilestoneUpdate(BaseModel):
    """Schema for updating milestones (all fields optional)."""

    name: str | None = Field(None, min_length=1, max_length=100)
    description: str | None = Field(None, min_length=1)
    status: str | None = Field(
        None, pattern="^(planned|in_progress|completed|cancelled)$"
    )
    start_date: datetime | None = None
    due_date: datetime | None = None
    issue_ids: list[UUID] | None = None
    tag_ids: list[UUID] | None = None
    document_ids: list[UUID] | None = None

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: str | None) -> str | None:
        """Validate milestone name."""
        if v is not None and not v.strip():
            raise ValueError("Name cannot be empty or whitespace")
        return v.strip() if v else v

    @field_validator("description")
    @classmethod
    def validate_description(cls, v: str | None) -> str | None:
        """Validate milestone description."""
        if v is not None and not v.strip():
            raise ValueError("Description cannot be empty or whitespace")
        return v.strip() if v else v


class MilestoneResponse(MilestoneBase):
    """Schema for milestone API responses."""

    id: UUID
    milestone_key: str  # Human-readable key (e.g., "CNTXT-M1")
    milestone_number: int  # Sequential number within project
    created_at: datetime
    updated_at: datetime
    issue_count: int = 0
    tag_count: int = 0
    document_count: int = 0

    model_config = ConfigDict(from_attributes=True)


class MilestoneSummary(BaseModel):
    """Summary information about a milestone."""

    id: UUID
    milestone_key: str  # Human-readable key
    name: str
    status: str
    due_date: datetime
    issue_count: int

    model_config = ConfigDict(from_attributes=True)